build:
  image: eu.phoria/drone-runner:35
  commands:
    - mv /drone/src/github.com/euphoria-io/ /drone/src/euphoria.io/
    - ci/test.sh build
    - mv /drone/src/euphoria.io/ /drone/src/github.com/euphoria-io/
  environment:
    - DB_HOST=127.0.0.1

compose:
  database:
    image: postgres

notify:
  webhook:
    image: chromakode/drone-webhook
    urls:
      - http://52.10.123.209:8082/dronehook

cache:
  mount:
    - .git
