package proto

import "fmt"

var (
	ErrAccessDenied                    = fmt.Errorf("access denied")
	ErrAccountIdentityInUse            = fmt.Errorf("account identity already in use")
	ErrAccountNotFound                 = fmt.Errorf("account not found")
	ErrAgentAlreadyExists              = fmt.Errorf("agent already exists")
	ErrAgentNotFound                   = fmt.Errorf("agent not found")
	ErrCapabilityNotFound              = fmt.Errorf("capability not found")
	ErrClientKeyNotFound               = fmt.Errorf("client key not found")
	ErrEditInconsistent                = fmt.Errorf("edit inconsistent")
	ErrEmailNotFound                   = fmt.Errorf("email not found")
	ErrEmailAlreadyDelivered           = fmt.Errorf("email already delivered")
	ErrInvalidConfirmationCode         = fmt.Errorf("invalid confirmation code")
	ErrInvalidNick                     = fmt.Errorf("invalid nick")
	ErrInvalidParent                   = fmt.Errorf("invalid parent ID")
	ErrInvalidUserID                   = fmt.Errorf("invalid user ID")
	ErrInvalidVerificationToken        = fmt.Errorf("invalid verification token")
	ErrLoggedIn                        = fmt.Errorf("logged in")
	ErrOTPAlreadyEnrolled              = fmt.Errorf("otp already enrolled")
	ErrOTPNotEnrolled                  = fmt.Errorf("otp not enrolled")
	ErrManagerNotFound                 = fmt.Errorf("manager not found")
	ErrMessageNotFound                 = fmt.Errorf("message not found")
	ErrMessageTooLong                  = fmt.Errorf("message too long")
	ErrNotLoggedIn                     = fmt.Errorf("not logged in")
	ErrPMNotFound                      = fmt.Errorf("pm not found")
	ErrPersonalIdentityAlreadyVerified = fmt.Errorf("personal identity already verified")
	ErrPersonalIdentityInUse           = fmt.Errorf("personal identity already in use")
	ErrRoomNotFound                    = fmt.Errorf("room not found")
)
